-- AQUI VÃO TODOS OS SCRIPTS USADOS NA CRIAÇÃO DAS TABELAS, COLUNAS, CONSTRAINTS PARA O MYSQL--

--1) TABELA CATEGORIAS

        CREATE TABLE CATEGORIAS(
            ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
            CATEGORIA VARCHAR(100) NOT NULL,
            ATIVO ENUM ('N','S') NOT NULL
        )

-- 2) TABELA PRODUTOS

        CREATE TABLE PRODUTOS(
            ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
            PRODUTO VARCHAR(100) NOT NULL,
            ESTOQUE INT NOT NULL,
            ESTOQUE_DT_ATUAL DATE NOT NULL,
            VALOR INT NOT NULL,
            ATIVO ENUM ('N','S'),
            ID_CATEGORIA INT NOT NULL
        )

        ALTER TABLE PRODUTOS ADD CONSTRAINT FK_IDCATEGORIA_PRODUTOS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)

-- 3) TABELA USUARIOS

        CREATE TABLE USUARIOS(
            ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
            USUARIO VARCHAR(20) NOT NULL,
            SENHA VARCHAR(20) NOT NULL,
            NOME VARCHAR(100) NOT NULL,
            CPF VARCHAR(11) NOT NULL,
            CELULAR VARCHAR(11) NOT NULL,
            DT_NASC DATE NOT NULL,
            EMAIL VARCHAR(100) NOT NULL,
            TIPO_USER ENUM (0,1) NOT NULL -- 1 É ADMIN
        )

-- 4) TABELA USUÁRIOS x PRODUTOS

        CREATE TABLE USUARIO_PRODUTO(
            ID_USUARIO INT NOT NULL,
            ID_PRODUTO INT NOT NULL,
            QUANTIDADE INT NOT NULL,
        )
        ALTER TABLE USUARIO_PRODUTO ADD CONSTRAINT FK_IDUSUARIO_USUARIOPRODUTO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
        ALTER TABLE USUARIO_PRODUTO ADD CONSTRAINT FK_IDPRODUTO_USUARIOPRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)
        ALTER TABLE USUARIO_PRODUTO ADD CONSTRAINT PK_IDUSUARIOIDPRODUTO_USUARIOPRODUTO PRIMARY KEY (ID_USUARIO, ID_PRODUTO)
